name: CI

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  ci-ubuntu:
    name: Build on Linux (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
      - name: install dependencies
        run: ./vcpkg.sh
      - name: Run CMake and vcpkg
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-multi-vcpkg'
          buildPreset: 'ninja-multi-vcpkg'
          buildPresetAdditionalArgs: "['--config Release']"
          testPreset: 'ninja-multi-vcpkg'
          testPresetAdditionalArgs: "['--config Release']"
      - name: build
        run: make build
      - name: build
        run: make test

  ci-mac:
    name: Build on MacOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - name: install dependencies
        run: ./vcpkg.sh
      - name: build
        run: make build
      - name: build
        run: make test
  fmt:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Run clang-format"
        uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: '18'
